[tool.poetry]
name = "caqtus-devices-siglent-sdg6022x"
version = "0.1.0"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"
packages = [{include = "caqtus_devices"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"
caqtus = {git = "https://github.com/light-scattering-io/caqtus.git"}
pyvisa = "^1.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
