[tool.poetry]
name = "caqtus-devices-ni6738-analog-card"
version = "1.4.0"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"
packages = [{ include = "caqtus_devices" }]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

nidaqmx = ">=0.9.0"

caqtus = { git = "https://github.com/light-scattering-io/caqtus.git" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
